AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance referencing network and security group stacks"

Parameters:
  CompanyName:
    Type: String
    Description: "Company or project name (e.g., example)"
    Default: "example"
  NetworkStackName:
    Type: String
    Description: "network.yaml Stack Name (exports SubnetId)"
  SecurityGroupStackName:
    Type: String
    Description: "sg.yaml Stack Name (exports SecurityGroupId)"
  ExecutorID:
    Type: String
    Description: "Example of CloudFormation Executor ID"
  ExecutorName:
    Type: String
    Description: "Executor Name (e.g. hamada)"

Resources:
  EC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub "${CompanyName}-keypem-poc-${ExecutorName}-server"
      Tags:
        - Key: Name
          Value: !Sub "${CompanyName}-keypem-poc-${ExecutorName}-server"
        - Key: Environment
          Value: poc
        - Key: OwnerID
          Value: !Ref ExecutorID
        - Key: Purpose
          Value: "Validate CloudFormation Deployment"

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-windows-latest/Windows_Server-2022-English-Full-Base}}"
      KeyName: !Ref EC2KeyPair
      SubnetId:
        Fn::ImportValue: !Sub "${NetworkStackName}-PublicSubnetId"
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${SecurityGroupStackName}-SecurityGroupId"
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
            DeleteOnTermination: true  # Auto-delete EBS when EC2 is terminated
            Tags:
              - Key: Name
                Value: !Sub "${CompanyName}-ebs-c-${ExecutorName}-server"
              - Key: Environment
                Value: poc
              - Key: OwnerID
                Value: !Ref ExecutorID
              - Key: Purpose
                Value: "Validate CloudFormation Deployment"
      Tags:
        - Key: Name
          Value: !Sub "${CompanyName}-ec2-poc-${ExecutorName}-server-${AWS::Region}"
        - Key: Environment
          Value: poc
        - Key: OwnerID
          Value: !Ref ExecutorID
        - Key: Purpose
          Value: "Validate CloudFormation Deployment"

Outputs:
  KeyPairId:
    Description: "KeyPair ID"
    Value: !GetAtt EC2KeyPair.KeyPairId
  KeyPairParameterPath:
    Description: "SSM Parameter path for private key"
    Value: !Sub "/ec2/keypair/${EC2KeyPair.KeyPairId}"
  InstanceId:
    Description: "EC2 Instance ID"
    Value: !Ref EC2Instance
  PublicIp:
    Description: "EC2 Public IP"
    Value: !GetAtt EC2Instance.PublicIp
